<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
 'Application\Module'                     => __DIR__ . '/Module.php',
 'Application\Contact\Dao'                => __DIR__ . '/src/Application/Contact/Dao.php',
 'Application\Contact\EmailNotificator'   => __DIR__ . '/src/Application/Contact/EmailNotificator.php',
 'Application\Contact\Entity'             => __DIR__ . '/src/Application/Contact/Entity.php',
 'Application\Contact\FormFactory'        => __DIR__ . '/src/Application/Contact/FormFactory.php',
 'Application\Controller\IndexController' => __DIR__ . '/src/Application/Controller/IndexController.php',
);
