<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Interactive Data ') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Interactive Data') ?></a>
                </div>
            </div>
        </nav>
        <div class="container">
			        <div class='system_messages'>
				        <?php
				        $flash = $this->flashMessenger();
				        $flash->setMessageOpenFormat('<div%s>
				                         <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				                         <ul><li>')
				        ->setMessageSeparatorString('</li><li>')
				        ->setMessageCloseString('</li></ul></div>');
				        
				        echo $flash->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
				        echo $flash->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
				        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
				        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
				        ?>
                    </div>
        
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by Interactive Data. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
